
export type WeeklyData = {
    week: number;
    image: string;
    hint: string;
    baby: {
        description: string;
    };
    mother: {
        description: string;
    };
};

// Simplified data for demonstration purposes.
export const pregnancyData: WeeklyData[] = [
    { week: 1, image: "https://placehold.co/600x600.png", hint: "pregnancy test", baby: { description: "Pregnancy is calculated from the first day of your last menstrual period. Conception has not yet occurred." }, mother: { description: "Your body is preparing for ovulation. This is the best time to start taking prenatal vitamins containing folic acid." } },
    { week: 2, image: "https://placehold.co/600x600.png", hint: "ovulation cycle", baby: { description: "Your ovary releases an egg (ovulation). If it meets a sperm, fertilization can happen." }, mother: { description: "You are ovulating. Some women may experience light spotting or a slight cramp." } },
    { week: 3, image: "https://placehold.co/600x600.png", hint: "fertilized egg", baby: { description: "If fertilization occurred, the fertilized egg (zygote) is rapidly dividing and traveling to the uterus." }, mother: { description: "The fertilized egg implants into your uterine lining. You won't feel this, but your body is starting to produce the pregnancy hormone hCG." } },
    { week: 4, image: "https://placehold.co/600x600.png", hint: "embryo development", baby: { description: "The blastocyst has implanted in your uterus and is now an embryo. The brain, spinal cord, and heart are beginning to form." }, mother: { description: "You might miss your period. Early pregnancy symptoms like fatigue and breast tenderness may begin. A home pregnancy test may now be positive." } },
    { week: 5, image: "https://placehold.co/600x600.png", hint: "embryo ultrasound", baby: { description: "Your baby's heart begins to beat and pump blood. Basic facial features start to appear." }, mother: { description: "Morning sickness may start. You may also experience increased urination and mood swings due to hormonal changes." } },
    { week: 6, image: "https://placehold.co/600x600.png", hint: "fetus development", baby: { description: "Arms and legs are starting to bud. The baby is about the size of a lentil." }, mother: { description: "Fatigue and nausea can be prominent. It's important to eat small, frequent meals and stay hydrated." } },
    { week: 7, image: "https://placehold.co/600x600.png", hint: "fetus hands feet", baby: { description: "Hands and feet are forming, looking like small paddles. The brain is developing rapidly." }, mother: { description: "You might have food cravings or aversions. Your sense of smell may be heightened." } },
    { week: 8, image: "https://placehold.co/600x600.png", hint: "fetus ultrasound", baby: { description: "The baby is constantly moving, though you can't feel it yet. Eyelids and the tip of the nose are forming." }, mother: { description: "It's a good time for your first antenatal visit. You may start to notice your clothes feeling tighter around the waist." } },
    { week: 9, image: "https://placehold.co/600x600.png", hint: "fetus organs", baby: { description: "All essential organs have begun to form. The baby is now officially a fetus." }, mother: { description: "You may feel very tired as your body is working hard to grow the baby. Dizziness can also occur." } },
    { week: 10, image: "https://placehold.co/600x600.png", hint: "fetus profile", baby: { description: "Fingers and toes are now distinct. The baby can open and close its fists." }, mother: { description: "Your uterus has grown to the size of a grapefruit. You might see a slight baby bump." } },
    { week: 11, image: "https://placehold.co/600x600.png", hint: "fetus outline", baby: { description: "The baby is almost fully formed. They are kicking, stretching, and even hiccupping." }, mother: { description: "Nausea may start to subside. Headaches are common due to hormonal shifts and increased blood volume." } },
    { week: 12, image: "https://placehold.co/600x600.png", hint: "fetus development", baby: { description: "Fingerprints have formed. The baby's reflexes are developing." }, mother: { description: "You've reached the end of the first trimester! The risk of miscarriage drops significantly." } },
    { week: 13, image: "https://placehold.co/600x600.png", hint: "fetus second trimester", baby: { description: "The baby's intestines are moving from the umbilical cord into their abdomen." }, mother: { description: "Welcome to the second trimester! You might start to feel more energetic." } },
    { week: 14, image: "https://placehold.co/600x600.png", hint: "fetus growth", baby: { description: "The baby can now squint, frown, and make other facial expressions." }, mother: { description: "Your baby bump may be more noticeable. You might experience round ligament pain as your uterus stretches." } },
    { week: 15, image: "https://placehold.co/600x600.png", hint: "fetus bones", baby: { description: "The skeleton is hardening, changing from soft cartilage to bone." }, mother: { description: "You might have a stuffy nose, which is a common pregnancy symptom caused by increased blood flow." } },
    { week: 16, image: "https://placehold.co/600x600.png", hint: "fetus hearing", baby: { description: "The baby can hear your voice. The eyes can sense light." }, mother: { description: "You might feel the first flutters of your baby's movements, known as quickening." } },
    { week: 17, image: "https://placehold.co/600x600.png", hint: "baby bump", baby: { description: "The baby is putting on fat, which will help regulate body temperature." }, mother: { description: "Your appetite might increase. Focus on nutritious food to support your baby's growth." } },
    { week: 18, image: "https://placehold.co/600x600.png", hint: "fetus kicking", baby: { description: "The nervous system is maturing. The baby is practicing swallowing." }, mother: { description: "Baby's movements are becoming stronger. You might have trouble sleeping comfortably." } },
    { week: 19, image: "https://placehold.co/600x600.png", hint: "fetus skin", baby: { description: "A greasy, white coating called vernix caseosa is forming on the skin to protect it." }, mother: { description: "You may experience skin changes, like the linea nigra, a dark line down your abdomen." } },
    { week: 20, image: "https://placehold.co/600x600.png", hint: "ultrasound scan", baby: { description: "You're halfway there! The baby is about the length of a banana." }, mother: { description: "A mid-pregnancy ultrasound is often done around this time to check the baby's anatomy." } },
    { week: 21, image: "https://placehold.co/600x600.png", hint: "fetus movement", baby: { description: "The baby's kicks and jabs are more definite now." }, mother: { description: "You might experience leg cramps, especially at night. Stay hydrated and stretch regularly." } },
    { week: 22, image: "https://placehold.co/600x600.png", hint: "fetus face", baby: { description: "The baby now looks like a miniature newborn. Eyebrows and eyelids are present." }, mother: { description: "Stretch marks may start to appear on your abdomen, breasts, or thighs." } },
    { week: 23, image: "https://placehold.co/600x600.png", hint: "fetus brain", baby: { description: "The sense of hearing is well-developed. The baby can be startled by loud noises." }, mother: { description: "Swelling in your ankles and feet can be common. Elevate your feet when possible." } },
    { week: 24, image: "https://placehold.co/600x600.png", hint: "fetus lungs", baby: { description: "The lungs are developing branches of the respiratory tree and cells that produce surfactant." }, mother: { description: "You should be tested for gestational diabetes between now and 28 weeks." } },
    { week: 25, image: "https://placehold.co/600x600.png", hint: "fetus hair", baby: { description: "The baby is growing more hair and adding more body fat." }, mother: { description: "You may experience backaches. Practice good posture and wear supportive shoes." } },
    { week: 26, image: "https://placehold.co/600x600.png", hint: "fetus eyes", baby: { description: "The baby's eyes are opening and can blink." }, mother: { description: "Your blood pressure may be slightly higher than in the first half of pregnancy." } },
    { week: 27, image: "https://placehold.co/600x600.png", hint: "fetus sleeping", baby: { description: "The baby has regular sleep and wake cycles." }, mother: { description: "You are nearing the end of the second trimester. You might feel short of breath as the uterus presses on your diaphragm." } },
    { week: 28, image: "https://placehold.co/600x600.png", hint: "fetus third trimester", baby: { description: "The baby's lungs are capable of breathing air, but would need medical help if born now." }, mother: { description: "Welcome to the third trimester! It's a good time to start antenatal classes." } },
    { week: 29, image: "https://placehold.co/600x600.png", hint: "baby growth", baby: { description: "The baby's bones are fully developed but still soft." }, mother: { description: "Heartburn and constipation are common complaints. Eat smaller meals and drink plenty of water." } },
    { week: 30, image: "https://placehold.co/600x600.png", hint: "fetus sight", baby: { description: "The baby's eyes can see, and pupils can constrict and dilate." }, mother: { description: "You may feel tired and have trouble getting comfortable at night. Sleep on your side with pillows for support." } },
    { week: 31, image: "https://placehold.co/600x600.png", hint: "fetus brain", baby: { description: "The brain is making trillions of connections. The baby is gaining weight rapidly." }, mother: { description: "You may leak a small amount of colostrum (early milk) from your breasts." } },
    { week: 32, image: "https://placehold.co/600x600.png", hint: "fetus position", baby: { description: "The baby is practicing breathing movements. They are getting crowded in the uterus." }, mother: { description: "You may experience Braxton Hicks contractions, which are 'practice' contractions." } },
    { week: 33, image: "https://placehold.co/600x600.png", hint: "fetus bones", baby: { description: "The baby's skeleton continues to harden. The skull bones are not yet fused." }, mother: { description: "It might be getting harder to bend over. Ask for help when you need it." } },
    { week: 34, image: "https://placehold.co/600x600.png", hint: "baby position", baby: { description: "Most babies are now in the head-down position in preparation for birth." }, mother: { description: "Fatigue may have returned. Rest as much as you can." } },
    { week: 35, image: "https://placehold.co/600x600.png", hint: "fetus lungs", baby: { description: "The lungs are nearly fully mature." }, mother: { description: "Your doctor visits may become more frequent now, perhaps every two weeks." } },
    { week: 36, image: "https://placehold.co/600x600.png", hint: "baby bump", baby: { description: "The baby is gaining about half a pound (about 225 grams) per week." }, mother: { description: "The baby may 'drop' into your pelvis, which can make breathing easier but increase pressure on your bladder." } },
    { week: 37, image: "https://placehold.co/600x600.png", hint: "fetus full term", baby: { description: "Your baby is now considered 'early term'. The vernix coating is getting thicker." }, mother: { description: "Keep an eye out for signs of labor, like regular contractions or your water breaking. Pack your hospital bag." } },
    { week: 38, image: "https://placehold.co/600x600.png", hint: "newborn baby", baby: { description: "The baby has a firm grasp. The brain and lungs continue to mature." }, mother: { description: "You might feel a mix of excitement and anxiety. Try to relax and get some rest." } },
    { week: 39, image: "https://placehold.co/600x600.png", hint: "pregnant belly", baby: { description: "Your baby is now considered 'full term' and is ready for life outside the womb." }, mother: { description: "Any day now! Continue to monitor your baby's movements and rest." } },
    { week: 40, image: "https://placehold.co/600x600.png", hint: "mother newborn", baby: { description: "The average newborn weighs about 7.5 pounds (3.4 kg) and is about 20 inches (51 cm) long." }, mother: { description: "Congratulations, you've reached your due date! Don't worry if the baby doesn't arrive on this exact day." } },
    { week: 41, image: "https://placehold.co/600x600.png", hint: "waiting baby", baby: { description: "The baby is still growing and may have longer hair and fingernails." }, mother: { description: "Your baby is now considered 'late term'. Your doctor may discuss inducing labor." } },
    { week: 42, image: "https://placehold.co/600x600.png", hint: "newborn infant", baby: { description: "The baby is ready to meet you!" }, mother: { description: "Your baby is 'post-term'. Labor will likely be induced to ensure the baby's safety." } },
];
